#!/usr/bin/env python3
"""Light mode for Home, derived from its dark rules.

The app was drawn dark first, with white-alpha glass, edges and text written
straight into its rules. This reads the top-level rules of index.html's
<style> and devices.css and, for every declaration that uses white, writes a
light-mode twin into a block between the LIGHT-BEGIN / LIGHT-END markers in the
same file (inside @media (prefers-color-scheme: light)), replacing the old one:

  glass panes (white gradients)      -> frosted white, about 4x stronger
  small white fills (discs, chips)   -> the same fills in dark ink
  hairline edges (inset 0 0 0 Npx)   -> dark hairlines
  black drop shadows                 -> a softer blue-grey, as light casts
  white text and borders             -> dark ink at the same strength
  #fff text on a coloured button     -> left white (KEEP_WHITE)

Run it after changing colours:  python3 house/tools/lightgen.py
"""
import re, pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent
INK = '28,32,40'
BLACK = re.compile(r'rgba\(\s*0\s*,\s*0\s*,\s*0\s*,\s*([0-9.]+)\s*\)')
SHADE = '30,40,60'
WHITE = re.compile(r'rgba\(\s*255\s*,\s*255\s*,\s*255\s*,\s*([0-9.]+)\s*\)')
KEEP_WHITE = ('.banner button', '.btn.primary', '.armbtn:not(.on)', '.pwr', '.ag.lit', '.tl-pwr.on')
BEGIN, END = '/* LIGHT-BEGIN (generated by tools/lightgen.py; edit the dark rules, then re-run) */', '/* LIGHT-END */'

def top_rules(css):
    """(selector, body) for top-level rules; @media, @keyframes etc. skipped."""
    out, i, n = [], 0, len(css)
    while i < n:
        j = css.find('{', i)
        if j < 0: break
        sel = css[i:j].strip()
        depth, k = 1, j + 1
        while k < n and depth:
            if css[k] == '{': depth += 1
            elif css[k] == '}': depth -= 1
            k += 1
        body = css[j + 1:k - 1]
        sel = re.sub(r'/\*.*?\*/', '', sel, flags=re.S).strip()
        if sel and not sel.startswith('@') and '{' not in body: out.append((sel, body))
        i = k
    return out

def decls(body):
    body = re.sub(r'/\*.*?\*/', '', body, flags=re.S)
    parts, buf, depth = [], '', 0
    for ch in body:
        if ch == '(': depth += 1
        elif ch == ')': depth -= 1
        if ch == ';' and depth == 0: parts.append(buf); buf = ''
        else: buf += ch
    parts.append(buf)
    return [(p.split(':', 1)[0].strip(), p.split(':', 1)[1].strip()) for p in parts if ':' in p and p.strip()]

def ink(a, k=1.0): return f'rgba({INK},{round(min(1, float(a) * k), 3)})'

def light(sel, prop, val):
    keep = any(sel.startswith(s) for s in KEEP_WHITE)
    if prop == 'color':
        if keep: return None
        if re.fullmatch(r'#fff(fff)?', val, re.I): return 'var(--text)'
        m = WHITE.fullmatch(val) or re.fullmatch(r'rgba\(\s*23[56]\s*,\s*23[56]\s*,\s*2(38|45)\s*,\s*([0-9.]+)\s*\)', val)
        if m: return ink(m.groups()[-1])
        return None
    if prop == 'box-shadow' and not WHITE.search(val) and not BLACK.search(val): return None
    if prop != 'box-shadow' and not WHITE.search(val): return None
    if prop.startswith('border'): return WHITE.sub(lambda m: ink(m.group(1), .8), val)
    if prop == 'box-shadow':
        # hairline edges go dark; highlights (offset rims) stay white
        def edge(s):
            if re.match(r'\s*inset\s+0\s+0\s+0\s+[0-9.]+px', s): return WHITE.sub(lambda m: ink(m.group(1), .55), s)
            if not s.strip().startswith('inset'): return BLACK.sub(lambda m: f'rgba({SHADE},{round(float(m.group(1)) * .4, 3)})', s)
            return s
        return ','.join(edge(s) for s in re.split(r',(?![^(]*\))', val))
    if prop.startswith('background'):
        if 'gradient' in val:   # glass: frosted white
            if keep: return None
            return WHITE.sub(lambda m: f'rgba(255,255,255,{round(min(.78, float(m.group(1)) * 4), 3)})', val)
        if keep: return None
        return WHITE.sub(lambda m: ink(m.group(1), .75), val)   # a small fill
    if prop in ('fill', 'stroke', 'outline-color', 'text-decoration-color'): return WHITE.sub(lambda m: ink(m.group(1)), val)
    return None

def block(css):
    rules = []
    for sel, body in top_rules(css):
        out = [(p, light(sel, p, v)) for p, v in decls(body)]
        out = [f'{p}: {v}' for p, v in out if v and v != body]
        if out: rules.append(f'    {sel} {{ {"; ".join(out)}; }}')
    return BEGIN + '\n  @media (prefers-color-scheme: light) {\n' + '\n'.join(rules) + '\n  }\n  ' + END

def apply(path, start=None, stop=None):
    text = path.read_text()
    a = text.find(start) + len(start) if start else 0
    b = text.find(stop) if stop else len(text)
    css = text[a:b]
    if BEGIN in css:   # the new block goes where the old one was, so hand-written rules after it still win
        i, j = css.index(BEGIN), css.index(END) + len(END)
        css = css[:i] + block(css[:i] + css[j:]) + css[j:]
    else:
        css = css.rstrip() + '\n  ' + block(css) + '\n'
    new = css[css.index(BEGIN):css.index(END)]
    path.write_text(text[:a] + css + text[b:])
    print(path.name, new.count('\n') - 2, 'rules')

apply(ROOT / 'index.html', '<style>', '</style>')
apply(ROOT / 'devices.css')
